In [1]:
import pandas

In [2]:
db = pandas.read_csv('marks.csv')

In [3]:
type(db)

pandas.core.frame.DataFrame

In [4]:
db

name  hrs  marks
0  vimal    7     70
1  rahul    5     50
2   eric    8     80
3  harry    2     20

In [5]:
# Target / DV
y = db["marks"]

In [6]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [7]:
# feature / IV
x = db['hrs']

In [8]:
x.shape

(4,)

In [9]:
type(x)

pandas.core.series.Series

In [10]:
x = x.values

In [11]:
type(x)

numpy.ndarray

In [12]:
x = x.reshape(4,1)

In [13]:
type(x)

numpy.ndarray

In [14]:
x.shape

(4, 1)

In [15]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
mind = LinearRegression()

In [18]:
# exp : model : linear function
# w : weight / coeffiecient
# model trained
mind.fit( x,  y)

LinearRegression()

In [19]:
mind.predict([[ 6 ]] )

array([60.])

In [20]:
# Linear function : y = wx
# w = 10

mind.coef_

array([10.])

In [22]:
import joblib

In [23]:
joblib.dump(mind , 'marks.pk1')

['marks.pk1']